@echo off
echo ===================================================
echo   Building Executable and Cleaning Project Workspace
echo ===================================================

:: 1. Pinpoint Python executable path
set "PYTHON_EXE="
if exist "%LocalAppData%\Programs\Python\Python314\python.exe" (
    set "PYTHON_EXE=%LocalAppData%\Programs\Python\Python314\python.exe"
) else if exist "%ProgramFiles%\Python314\python.exe" (
    set "PYTHON_EXE=%ProgramFiles%\Python314\python.exe"
) else (
    for /d %%I in ("%LocalAppData%\Python\pythoncore-*") do (
        if exist "%%I\python.exe" set "PYTHON_EXE=%%I\python.exe"
    )
)

if not defined PYTHON_EXE (
    echo Python installation could not be located. Aborting build.
    exit /b
)

:: 2. Execute PyInstaller build targeting app.pyw
"%PYTHON_EXE%" -m PyInstaller --noconsole --onefile --name="YouTube_Downloader_GUI" app.pyw

:: 3. Post-Build Workspace Consolidation and Clean-up
if exist "dist\YouTube_Downloader_GUI.exe" (
    echo.
    echo Compilation successful. Extracting binary...
    
    :: Move the executable up to the parent project directory
    move /y "dist\YouTube_Downloader_GUI.exe" "%~dp0YouTube_Downloader_GUI.exe"
    
    echo Cleaning up project source files and build artifacts...
    
    :: Delete python code files explicitly
    if exist "app.pyw" del /f /q "app.pyw"
    if exist "install_and_build.py" del /f /q "install_and_build.py"
    
    :: Delete temporary build directories generated by PyInstaller
    if exist "build" rmdir /s /q "build"
    if exist "dist" rmdir /s /q "dist"
    if exist "YouTube_Downloader_GUI.spec" del /f /q "YouTube_Downloader_GUI.spec"
    
    echo Cleanup complete. Finalizing setup window...
    
    :: Self-deleting command routine for the batch file
    (goto) 2>nul & del "%~f0"
) else (
    echo.
    echo Build failed. Source files preserved for debugging purposes.
    pause
)
